server:
  port: 8081

azure:
  activedirectory:
    tenant-id: b9b9b0d6-22fd-410b-af7b-790281cbc0bc
    client-id: 9d89d95b-d523-4e76-9f9d-e5aadeb697c8
    client-secret: 136a3d93-921d-46a2-9b0d-4e8a53ea592f
    app-id-uri: api://9d89d95b-d523-4e76-9f9d-e5aadeb697c8
    authorization-clients:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
